name: simple_pipeline

on: push

jobs:
  Build:

    runs-on: ubuntu-latest
    
    steps:

      - name: Check out Code
        uses: actions/checkout@v2

      - name: echoing the file name
        env:
          Filename: $GITHUB_WORKFLOW:$GITHUB_RUN_ID
          File: $GITHUB_WORKFLOW
          Reponame: nbharathkumara

        run: |
          echo $Filename
          echo $File
          echo $Reponame
      
      - name: Building Docker Images
        run: |
          docker image build -t $Filename . 
          docker image tag $Filename $Reponame/$Filename
          docker image tag $Filename $Reponame/$File:latest

  Push:
    needs: Build
    
    runs-on: ubuntu-latest

    steps:

      - name: Pushing Image onto Docker Hub
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
          docker image push $Reponame/$Filename
          docker image push $Reponame/$File:latest
          docker image rmi $Filename $Reponame/$Filename $Reponame/$File:latest

  Deploy:      
  
    needs: Push
    
    runs-on: ubuntu-latest
    
    steps:

      - name: Deploying the Docker
        env: 
          PRIVATE_KEY: ${{secrets.SSH_KEY}}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.SSH_USER}}
          
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker container rm -f bkob-server
            docker system prune -a -f
            docker run -p 80:80 -d --name bkob-server $Reponame/$File:latest
            '