name: example

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    
    steps:
      - name: list files
        run: ls -la
      
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: list files
        run: ls -lR
        
