name: simple_pipeline

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Check out Code
        uses: actions/checkout@v2

      - name: echoing the file name
        run: |
          echo $GITHUB_WORKFLOW
          echo $GITHUB_RUN_ID
      
      - name: Building Docker Images
        run: |
          docker image build -t $GITHUB_WORKFLOW:v$GITHUB_RUN_ID . 
          docker image tag $GITHUB_WORKFLOW:v$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:v$GITHUB_RUN_ID
          docker image tag $GITHUB_WORKFLOW:v$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:latest
      
      - name: listing the files
        run: docker images
      
      - name: Display Creds
        run: |
          echo ${{secrets.DOCKER_USER}}
          echo ${{secrets.DOCKER_PASSWORD}}


