name: simple_pipeline

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: connecting to ssh server
        env: 
          PRIVATE_KEY: ${{secrets.SSH_KEY}}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.SSH_USER}}
          
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            id
            ls -la
            pwd
          '
          
