name: simple_pipeline

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Check out Code
        uses: actions/checkout@v2

      - name: echoing the file name
        run: |
          echo $GITHUB_WORKFLOW
          echo $GITHUB_RUN_ID
      
      - name: Building Docker Images
        run: |
          docker image build -t $GITHUB_WORKFLOW:$GITHUB_RUN_ID . 
          docker image tag $GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:$GITHUB_RUN_ID
          docker image tag $GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:latest
      
      - name: Pushing Image onto Docker Hub
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
          docker image push nbharathkumara/$GITHUB_WORKFLOW:$GITHUB_RUN_ID
          docker image push nbharathkumara/$GITHUB_WORKFLOW:latest
          docker image rmi $GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:$GITHUB_RUN_ID nbharathkumara/$GITHUB_WORKFLOW:latest

